# INITIAL SETTINGS
data_directory: ./Data/
file_directory: ./Files/
basic_data: BasicData.csv
master_data: MasterData.csv
test_size: 0.2
model_directory: ./TrainedModel/
dnn_model_name: dnn_best_model.hdf5
cnn_model_name: cnn_best_model.hdf5
